### ISSUE TITLE
Got an error when running deepspeed benchmark testing on local env

### ISSUE THREAD

**Issue by qyhdt** [pytorch/torchsnapshot#138]
### 🚀 The feature

Hi, recently I did a benchmark testing on my local env, it gives me below error:
![image](https://user-images.githubusercontent.com/7843730/232689489-85491ab2-2c46-44e6-a280-864732f691ab.png)
obviously it missed a package called tricks, then I get into the root folder and execute ： pip install .
but the tricks package did not show up in the target folder (site-packages/torchsnapshot), finally I found that there is no __init__.py file under tricks folder. So when you running pip install . , the tricks folder was not able to be installed to the site-packages/torchsnapshot folder.
To fix this issue needs to add an __init__.py file under tricks folder.

### Motivation, pitch

To be convenient for the people who want to run benchmark on their local or somewhere envs.

**Comment by ananthsub** [comment]
Thanks for filing this issue @qyhdt. I will send out a fix shortly.
